# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "tfr:///terraform-google-modules/kubernetes-engine/google//modules/private-cluster?ref=v28.0.0"
}

include "root" {
  path = find_in_parent_folders()
}
